set(GSTREAMER_PLUGINS_CORE coreelements coretracers adder app audioconvert audiomixer audiorate audioresample audiotestsrc compositor gio overlaycomposition pango rawparse typefindfunctions videoconvertscale videorate videotestsrc volume autodetect videofilter insertbin switchbin fallbackswitch gopbuffer livesync originalbuffer rsinter rstracers streamgrouper threadshare togglerecord)
set(GSTREAMER_PLUGINS_CODECS subparse ogg theora vorbis opus adaptivedemux2 alaw amrnb amrwbdec apetag audioparsers auparse avi dv flac flv flxdec icydemux id3demux isomp4 jpeg lame matroska mpg123 mulaw multipart png speex taglib vpx wavenc wavpack wavparse xingmux y4menc adpcmdec adpcmenc assrender bz2 codecalpha codectimestamper dash dvbsubenc dvbsuboverlay dvdspu hls id3tag ivfparse midi mxf openh264 opusparse pcapparse pnm rfbsrc siren smoothstreaming subenc transcode videoparsersbad y4mdec jpegformat gdp openjpeg spandsp sbc zbar rsvg svtav1 x265 androidmedia cdg claxon dav1d rsclosedcaption ffv1 fmp4 mp4 gif hsv lewton rav1e json rspng regex textwrap textahead)
set(GSTREAMER_PLUGINS_ENCODING encoding)
set(GSTREAMER_PLUGINS_NET tcp rtsp rtp rtpmanager soup udp dtls netsim rist rtmp2 rtpmanagerbad rtponvif sctp sdpelem srtp srt webrtc nice rtspclientsink aws hlssink3 hlsmultivariantsink mpegtslive ndi quinn rsonvif raptorq rsrelationmeta reqwest rsrtp rsrtsp webrtchttp rswebrtc)
set(GSTREAMER_PLUGINS_PLAYBACK playback uriplaylistbin)
set(GSTREAMER_PLUGINS_SYS opengl ipcpipeline tinyalsa opensles)
set(GSTREAMER_PLUGINS_EFFECTS alpha alphacolor audiofx cairo cutter debug deinterlace dtmf effectv equalizer gdkpixbuf imagefreeze interleave level multifile replaygain shapewipe smpte spectrum videobox videocrop videomixer accurip aes aiff audiobuffersplit audiofxbad audiolatency audiomixmatrix autoconvert bayer coloreffects closedcaption debugutilsbad fieldanalysis freeverb gaudieffects geometrictransform inter interlace ivtc legacyrawparse proxy removesilence segmentclip smooth speed soundtouch timecode videofiltersbad videoframe_audiolevel videosignal webrtcdsp ladspa rsaudiofx rsvideofx)
set(GSTREAMER_PLUGINS_VIS goom goom2k1 audiovisualizers)
set(GSTREAMER_PLUGINS_CAPTURE camerabin)
set(GSTREAMER_PLUGINS_CODECS_RESTRICTED asfmux dtsdec mpegpsdemux mpegpsmux mpegtsdemux mpegtsmux voaacenc a52dec asf dvdsub dvdlpcmdec realmedia x264 libav)
set(GSTREAMER_PLUGINS_NET_RESTRICTED rtmp)
set(GSTREAMER_PLUGINS_VULKAN vulkan)
set(GSTREAMER_PLUGINS_GES nle ges)
